contact/urls.py
from contact import views
from django.urls import path

app_name = 'contact'

urlpatterns = [
    path('', views.login, name='login'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('logout/', views.user_logout, name='logout'),
    path('account/', views.account, name='account'),
    path('account_update/', views.account_update, name='account_update'),
    path('account_delete/', views.account_delete, name='account_delete'),
    path('password_reset/', views.password_reset, name='password_reset'),




    path('index/', views.index, name='index'),
    path('my_contact/', views.my_contact, name='my_contact'),
    path('search/', views.search, name='search'),

    path('contact/<int:contact_id>/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),





]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone = models.CharField(max_length=30)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL,
        blank=True, null=True,)
    
    owner = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL,
        blank=True, null=True,)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/forms.py
from django.core.exceptions import ValidationError
from django import forms
from contact.models import Contact

class ContactForm(forms.ModelForm):
    picture = forms.ImageField(
        required=False,
        widget=forms.FileInput(
            attrs={
                'accept': 'image/*',
            }
        )
    )

    

    class Meta:
        model = Contact
        fields = ('first_name', 'last_name', 'phone', 'email', 'description', 'category', 'picture')

    def clean(self):
        phone = self.cleaned_data.get('phone')

        if len(phone) > 20:
            self.add_error('phone', ValidationError('Numero de telefone invalido', code='invalid'))

        return super().clean()
    
    

contact/views/contact_forms.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from contact.forms import ContactForm
from contact.models import Contact



def create(request):    
    if request.user.is_authenticated:
        form_action = reverse('contact:create')

        if request.method == 'POST':
            form = ContactForm(request.POST, request.FILES)

            context = {
                'form': form,
                'form_action': form_action,
                'button_text': 'Create Contact'
            }

            if form.is_valid():
                contact = form.save(commit=False)
                contact.owner = request.user
                contact.save()
                return redirect('contact:index')

            return render(
                request, 
                'contact/create.html',
                context
            )

        context = {
            'form': ContactForm(),
            'form_action': form_action,
            'button_text': 'Create Contact'
        }

        return render(
            request, 
            'contact/create.html',
            context
        )
    else:
        return redirect('contact:login')


def update(request, contact_id): 
    if request.user.is_authenticated:
        contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)   
        form_action = reverse('contact:update', args=(contact_id,))

        if request.method == 'POST':
            form = ContactForm(request.POST, request.FILES, instance=contact,)

            context = {
                'form': form,
                'form_action': form_action,
                'button_text': 'Save'
            }

            if form.is_valid():
                contact = form.save()
                return redirect('contact:index',)

            return render(
                request, 
                'contact/create.html',
                context
            )

        context = {
            'form': ContactForm(instance=contact),
            'form_action': form_action,
            'button_text': 'Save'
        }

        return render(
            request, 
            'contact/create.html',
            context
        )
    else:
        return render(request, 'global/login.html')


def delete(request, contact_id): 
    if request.user.is_authenticated:
        contact = get_object_or_404(Contact, pk=contact_id, show=True, owner=request.user)

        confirmation = request.POST.get('confirmation', 'no')

        if confirmation == 'yes':
            contact.delete() 
            return redirect('contact:my_contact')


        return render(
            request, 
            'contact/contact.html',
            {
                'contact': contact,
                'confirmation': confirmation ,
            },
        )
    else:
        return render(request, 'global/login.html')

contact/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from contact.models import Contact
from django.core.paginator import Paginator
from django.views.decorators.cache import never_cache



def index(request):
    if request.user.is_authenticated:
        contacts = Contact.objects.filter(show=True).order_by('-id')

        paginator = Paginator(contacts, 10)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)


        context = {
            'page_obj': page_obj,
            'site_title': 'Contatos - '
        }

        return render(
            request, 
            'contact/index.html',
            context
        )
    else:
        return render(request, 'global/login.html')
    
def my_contact(request):
    if request.user.is_authenticated:
        user = request.user
        contacts = Contact.objects.filter(show=True, owner=user).order_by('-id')

        paginator = Paginator(contacts, 10)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)


        context = {
            'page_obj': page_obj,
            'site_title': 'Contatos - ',
            'header_type': 'user_contact',
        }

        return render(
            request, 
            'contact/my_contact.html',
            context
        )
    else:
        return render(request, 'global/login.html')



def contact(request, contact_id):
    if request.user.is_authenticated:
        single_contact = get_object_or_404(Contact, pk=contact_id)

        contact_name = f'{single_contact.first_name} {single_contact.last_name}'

        context = {
            'contact': single_contact,
            'site_title': f'{contact_name} - '

        }

        return render(
            request, 
            'contact/contact.html',
            context
        )
    else:
        return render(request, 'global/login.html')
    

def search(request):
        if request.user.is_authenticated:
            search_value = request.GET.get('q', '').strip()

            if search_value == '':
                return redirect('contact:index')

            contacts = Contact.objects.filter(show=True)\
            .filter(
                    Q(first_name__icontains=search_value) |
                    Q(last_name__icontains=search_value) 
                    )\
            .order_by('-id')

            paginator = Paginator(contacts, 10)
            page_number = request.GET.get("page")
            page_obj = paginator.get_page(page_number)


            context = {
                'page_obj': page_obj,
                'site_title': 'Contatos - '
            }

            return render(
                request, 
                'contact/index.html',
                context
    )
        else:
            return render(request, 'global/login.html')

    

contact/views/user_views.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, logout, update_session_auth_hash
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as login_django
from django.contrib.auth.decorators import login_required

def login(request):
    errors = {}
    if request.method == "GET":
        context = {'site_title': 'Contatos - '}

        return render(
            request, 
            'global/login.html',
            context
        )
    username = request.POST.get('username')
    password = request.POST.get('password')

    user = authenticate(username=username, password=password)

    if user == None:
        errors['login'] = 'Nome de usuario ou senha invalidas'

    
    if errors:
        return render(request, 'global/login.html', {'errors': errors})
        
    login_django(request, user)

    return redirect('contact:index')



def cadastro(request):
    errors = {}
    if request.method == "GET":
        context = {'site_title': 'Contatos - '}

        return render(
            request, 
            'global/cadastro.html',
            context
        )
    else:
        username = request.POST.get('username')
        email = request.POST.get('registerEmail')
        password = request.POST.get('registerPassword')
        confirm_password = request.POST.get('confirmPassword')


        if User.objects.filter(username=username).exists():
            errors['Username'] = 'Esse nome já esta sendo utilizado'
        
        if User.objects.filter(email=email).exists():
            errors['Email'] = 'Esse E-mail já foi registrado'


        if len(password) < 8:
            errors['Password'] = 'A senha precisa ter pelo menos 8 caracteres'

        if password != confirm_password:
            errors['Confirmpassword'] = 'As senhas não coincidem'

        if errors:
            return render(request, 'global/cadastro.html', {'errors': errors})

        user = User.objects.create_user(username=username, email=email, password=password)
        user.save()   

        context = {'site_title': 'Contatos - '}
        return render(
            request, 
            'global/login.html',
            context
        )


def user_logout(request):
    logout(request)
    return redirect('contact:login')


def account(request):
        context = {'site_title': 'Contatos - '}
        return render(
            request, 
            'global/usuario/account.html',
            context
        )

def account_update(request):
    if request.method == 'POST':

        first_name = request.POST.get('First_Name')
        last_name = request.POST.get('Last_Name')
        email = request.POST.get('Email')


        user = request.user


        if first_name:
            user.first_name = first_name
        if last_name:
            user.last_name = last_name
        if email:
            user.email = email
        
        user.save()

        return redirect('contact:account')

    context = {'site_title': 'Contatos - '}
    return render(request, 'global/usuario/account_update.html', context)






def account_delete(request):
    confirmation = request.POST.get('confirmation', 'no')
    user = request.user

    if confirmation == 'yes':
        user.delete() 
        return redirect('contact:login')


    return render(
        request, 
        'global/usuario/account.html',
        {
            'confirmation': confirmation ,
        },
    )



def password_reset(request):

    if request.method == "POST":
        errors = {}

        new_password = request.POST.get('password')
        confirm_password = request.POST.get('confirmpassword')


        if new_password != confirm_password:
            errors['password'] = 'As senhas são diferentes'
        elif not new_password or not confirm_password:
            errors['password'] = 'As senhas não podem estar vazia'
        elif len(new_password) < 8:
            errors['password'] = 'As senhas precisam ter mais de 8 caracteres'
        else:
            user = request.user
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)  # Atualiza a sessão do usuário
            return redirect('contact:account')  # Redireciona após alteração bem-sucedida


        context = {
            'errors': errors,
            'site_title': 'Contatos - ',
        }
        return render(request, 'global/usuario/password_reset.html', context)

    # Se a solicitação for GET, apenas renderize o template
    context = {'site_title': 'Contatos - '}
    return render(request, 'global/usuario/password_reset.html', context)


        

contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="single-contact">
    <h1 class="single-contact-name">
      {{ contact.first_name }} {{ contact.last_name }}
    </h1>

    <p><b>ID:</b> {{ contact.id }}</p>
    <p><b>E-mail:</b> {{ contact.email }}</p>
    <p><b>Phone:</b> {{ contact.phone }}</p>
    <p><b>Created Date:</b> {{ contact.created_date }}</p>
    <p><b>Description:</b> {{ contact.description }}</p>
    <p><b>Category:</b> {{ contact.category.name }}</p>

    {% if contact.picture %}
      <p>
        <img src="{{ contact.picture.url }}" alt="{{ contact.first_name }} {{ contact.last_name }}">
      </p>
    {% endif %}

    {% if user == contact.owner %}
    <div class="contact-links">
      <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Update</a>

      <form action="{% url 'contact:delete' contact.id %}" method="post">
        {% csrf_token %}
        {% if confirmation == 'no' %}
          <input type="hidden" name="confirmation" value="yes">
          <button class="btn btn-link btn-delete" type="submit">Confirm</button>
        {% else %}
          <button class="btn btn-link btn-delete" type="submit">Delete</button>
        {% endif %}
      </form>
    </div>
  </div>
  {% endif %}
{% endblock content %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
<div class="form-wrapper">

  <h2>Contact</h2>

  <form action="{{form_action}}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form-content">

      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
        {{ field.errors }}


        {% if field.name == 'picture' and field.value.url %}
        <div class="form-group">
          <img src="{{ field.value.url }}" alt="">
        </div>
      {% endif %}
      </div>
      {% endfor %}
    </div>

    {% if form.non_field_errors %}
    <div class="form-content">
      <div class="form-group">
        <div class="message error">
          {{ form.non_field_errors }}
        </div>
      </div>
    </div>
    {% endif %}

    <div class="form-content">
      <div class="form-group">
        <button class="btn" type="submit">{{button_text}}</button>
      </div>
    </div>

  </form>
</div>
{% endblock content %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}

{% if page_obj %}
<style>
    .contacts-table {
        font-size: 20px; /* Ajuste para o tamanho desejado */
    }
    .table-header {
        font-size: 20px; /* Tamanho dos cabeçalhos */
    }
    .table-cel {
        padding: 15x; /* Aumenta o espaçamento interno das células */
    }
    .table-cel a {
        color: #0000EE !important;
        text-decoration: none !important;
    }


</style>

<div class="responsive-table">
    <table class="contacts-table">
        <caption class="table-caption">
            All Contacts
        </caption>

        <thead>
            <tr class="table-row table-row-header">
                <th class="table-header">ID</th>
                <th class="table-header">First Name</th>
                <th class="table-header">Last Name</th>
                <th class="table-header">Phone</th>
                <th class="table-header">E-mail</th>

            </tr>
        </thead>

        <tbody>
            {% for contact in page_obj %}
            <tr class="table-row">
                <td class="table-cel">

                <a href="{% url 'contact:contact' contact.id %}">
                    {{contact.id}}
                </a>
                
                </td>
                <td class="table-cel">
                    {{contact.first_name}}
                                    
                </td>
                <td class="table-cel">
                    {{contact.last_name}}                

                                    
                </td>
                <td class="table-cel">
                    {{contact.phone}}

                                
                </td>
                <td class="table-cel">
                    {{contact.email}}
                                
                </td>


                </td>
            </tr>
            {% endfor %}
        </tbody>


    </table>
</div>
{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        Nenhum contato encontrado
    </h1>

</div>

{% endif %}
{% endblock content %}

contact/templates/contact/my_contact.html
{% extends 'global/base.html' %}

{% block content %}

{% if page_obj %}
<style>
    .contacts-table {
        font-size: 20px; /* Ajuste para o tamanho desejado */
    }
    .table-header {
        font-size: 20px; /* Tamanho dos cabeçalhos */
    }
    .table-cel {
        padding: 15x; /* Aumenta o espaçamento interno das células */
    }
</style>

<div class="responsive-table">
    <table class="contacts-table">
        <caption class="table-caption">
            All Contacts
        </caption>

        <thead>
            <tr class="table-row table-row-header">
                <th class="table-header">ID</th>
                <th class="table-header">First Name</th>
                <th class="table-header">Last Name</th>
                <th class="table-header">Phone</th>
                <th class="table-header">E-mail</th>

            </tr>
        </thead>

        <tbody>
            {% for contact in page_obj %}
            <tr class="table-row">
                <td class="table-cel">

                <a href="{% url 'contact:contact' contact.id %}">
                    {{contact.id}}
                </a>
                
                </td>
                <td class="table-cel">
                    {{contact.first_name}}
                                    
                </td>
                <td class="table-cel">
                    {{contact.last_name}}                

                                    
                </td>
                <td class="table-cel">
                    {{contact.phone}}

                                
                </td>
                <td class="table-cel">
                    {{contact.email}}
                                
                </td>


                </td>
            </tr>
            {% endfor %}
        </tbody>


    </table>
</div>
{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        Nenhum contato encontrado
    </h1>

</div>

{% endif %}
{% endblock content %}